### ISSUE TITLE
CSS Hamburger Menu

### ISSUE THREAD

**Issue by LizHamburger** [LizHamburger/portfolio#1]
@lukeowaincharles started working on a CSS Hamburger menu for me as it's currently too advanced for me.

It's not linked up and needs JS to fix it.

**Comment by lukeowaincharles** [comment]
Please see new branch `feature-menu`. Description below as what will need to be done:

Firstly, you'll need to add a link to jQuery in the `head` of every file, using this link `<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>`
Once this has been added you will be able to use `jQuery` within the `JS` files.

You will then need to set up a `js` folder within `src`, within this folder create a `main.js` file. This is where things get fun. You can `addClass`, `removeClass` or even `toggleClass`'s onto existing `html` elements.

I have added some jQuery in the `feature-menu` branch.

There is still some `CSS` to be done to finish the menu, I'll update this feature branch with ideas on how to do that later.

**Comment by LizHamburger** [comment]
Thanks!
